language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

matrix:
  include:
    - python: 2.6
      dist: precise
    - python: 3.3
      dist: precise

install: python setup.py bootstrap install

before_script: pip install nose

script:
  - python runtests.py -v
  - nosetests -v
